name: Glenn Gibson
favicon: null
layout_spectrum: 0.96288
typography_spectrum: 0.58199
title: 'Glenn Gibson | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0035a9'
    - '#005cf6'
    - '#00bdfd'
    - '#771f1a'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
