name: Glenn Gibson
favicon: null
layout_spectrum: 0.38441613712348044
typography_spectrum: 0.58199
title: 'Glenn Gibson | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#bdbdbd'
    - '#636361'
    - '#9d9d9b'
    - '#f1f1f3'
  brandStrength: 0.5
  lightness: 0.9042698089033365
  saturation: 0.6757205810863525
  rhythmicContrast: 0.35116516589187086
purpose: []
