name: Glenn Gibson
favicon: null
layout_spectrum: 0.96288
typography_spectrum: 0.58199
title: 'Glenn Gibson | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#fbfcfd'
    - '#847f80'
    - '#686263'
    - '#e1dee1'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
