name: Glenn Gibson
favicon: null
layout_spectrum: 0.38441613712348044
typography_spectrum: 0.58199
title: 'Glenn Gibson | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131211'
    - '#9ea7af'
    - '#6c7881'
    - '#932e2e'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0
purpose: []
