typography_spectrum: 0.58199
color:
  brandColors:
    - '#101010'
    - '#fbfcfd'
    - '#847f80'
    - '#686263'
    - '#e1dee1'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.96288
analytics:
  google: null
  facebook: null
  twitter: null
name: Glenn Gibson
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Glenn Gibson '
description: photographer | director | dop
purpose: []
